AnacondaRecipes/conda-feedstock

recipe/meta.yaml
Not sure if this is all that is needed. Anyone interesting in reviewing this?
=> conda 4.10.2

recipe/meta.yaml
Release: https://github.com/conda/conda/releases/tag/4.13.0
Docs: https://docs.conda.io/projects/conda/en/latest/release-notes.html#id1
=> Update to 4.13.0.

recipe/meta.yaml
To match https://github.com/conda/conda/pull/11643
=> update minimum requests

recipe/meta.yaml
Xref: https://github.com/conda/conda/issues/11698, https://github.com/conda-forge/conda-feedstock/pull/170, https://github.com/conda/conda/pull/11700
=> Require `toolz` & soften `cytoolz` dependency (copy)

recipe/meta.yaml, recipe/run_test.sh
Refs https://github.com/conda/conda/issues/11932
https://github.com/conda-forge/conda-feedstock/pull/181
=> Update to 22.11.0

recipe/meta.yaml
Follow up to https://github.com/AnacondaRecipes/conda-feedstock/pull/17
=> Add tqdm to run section as well and relaxed pin on ruaml.yaml.

recipe/meta.yaml
Xrefs https://github.com/conda/conda/issues/11932
=> Update to 22.11.1

recipe/meta.yaml
- Release issue https://github.com/conda/conda/issues/12224
- Release PR https://github.com/conda/conda/pull/12249
- Release https://github.com/conda/conda/releases/tag/23.1.0
=> Bump to 23.1.0

recipe/meta.yaml, recipe/patches/01-deprecations-version-fallback.patch
=> conda 23.3.0 release

recipe/meta.yaml
Bumping conda version. This patch includes a hotfix from this PR:
- https://github.com/conda/conda/pull/12874
=> Bump conda version to 23.5.1

recipe/meta.yaml
Bumping conda version. This patch includes a fix from this PR:
- https://github.com/conda/conda/pull/12880
=> Bump conda version to 23.5.2

recipe/meta.yaml
Bumping conda version for July 2023 release.
xrefs https://github.com/conda/conda/issues/12849
=> Bump to 23.7.0

recipe/meta.yaml
Hotfix correcting `--json`/`--debug` regression https://github.com/conda/conda/issues/12928
Xref https://github.com/conda/conda/issues/12849
Changelog: https://github.com/conda/conda/blob/23.7.1/CHANGELOG.md
=> Bump version to 23.7.1

recipe/meta.yaml
Hotfix correcting --json/--debug for `conda env`
Xref https://github.com/conda/conda/issues/12849
Changelog https://github.com/conda/conda/blob/23.7.2/CHANGELOG.md
=> Bump to 23.7.2

recipe/meta.yaml
Requires https://github.com/conda/conda-libmamba-solver/issues/350
Xrefs https://github.com/conda/conda/issues/13156
Xrefs https://github.com/conda-forge/conda-feedstock/pull/224
=> Bump to 23.10.0.

recipe/meta.yaml
conda 24.1.0
- https://github.com/conda/conda/issues/13486
=> Bump to 24.1.0

abs.yaml
correct abs conf to build 3.12
=> correct abs conf

abs.yaml, recipe/meta.yaml
Changes:
- increase build number
- enable tests in CI
Note: publishing this is not required, but at least it shows the tests do pass.
=> enable tests

recipe/meta.yaml
conda 24.1.1
- [PKG-4051](https://anaconda.atlassian.net/browse/PKG-4051)
- [Upstream repository](https://github.com/conda/conda/issues/13486)
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.1.1)
- n/a
- Patch release to fix zstandard error handling
[PKG-4051]: https://anaconda.atlassian.net/browse/PKG-4051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> conda 24.1.1

recipe/meta.yaml
conda 24.9.2
- [PKG-5944](https://anaconda.atlassian.net/browse/PKG-5944) 
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.9.2)
- n/a
- n/a
[PKG-5944]: https://anaconda.atlassian.net/browse/PKG-5944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> conda 24.9.2 version bump

recipe/meta.yaml
conda 24.11.2
- [PKG-6668](https://anaconda.atlassian.net/browse/PKG-6668) 
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.11.2)
- n/a
- Bump to latest patch release
[PKG-6668]: https://anaconda.atlassian.net/browse/PKG-6668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> conda 24.11.2

recipe/meta.yaml
conda 24.11.3
- [PKG-6718](https://anaconda.atlassian.net/browse/PKG-6718)
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.11.3)
- n/a
- Bump to latest patch release
[PKG-6718]: https://anaconda.atlassian.net/browse/PKG-6718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> conda 24.11.3

recipe/meta.yaml
conda 25.1.0
- [PKG-6820](https://anaconda.atlassian.net/browse/PKG-6820) 
- [Upstream changelog/diff](https://github.com/conda/conda/compare/24.11.3...25.1.0)
[PKG-6820]: https://anaconda.atlassian.net/browse/PKG-6820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump to 25.1.0.

recipe/meta.yaml
conda 25.1.1
- [PKG-6944](https://anaconda.atlassian.net/browse/PKG-6944) 
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/25.1.1)
- n/a
- Bump to latest patch release
[PKG-6944]: https://anaconda.atlassian.net/browse/PKG-6944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> conda 25.1.1

abs.yaml, recipe/meta.yaml
conda 25.3.0
- [PKG-7429](https://anaconda.atlassian.net/browse/PKG-7429)
- [Upstream repository](https://github.com/conda/conda/issues/14632)
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/25.3.0)
- n/a
- Latest release of `conda` with Python 3.9-3.13 support
[PKG-7429]: https://anaconda.atlassian.net/browse/PKG-7429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> conda 25.3.0

abs.yaml, recipe/meta.yaml
=> re-enable tests

recipe/meta.yaml
conda 25.3.1
- [PKG-7869](https://anaconda.atlassian.net/browse/PKG-7869) 
- [Upstream changelog/diff](https://github.com/conda/conda/issues/14632)
- n/a
- Bump to latest patch release
[PKG-7869]: https://anaconda.atlassian.net/browse/PKG-7869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> conda 25.3.1

recipe/meta.yaml
- https://github.com/conda/conda/releases/tag/25.5.0
- https://github.com/conda/conda/issues/14838
Changes required for the latest release of conda (25.5.0)
=> 25.5.0 Release
