recipe/meta.yaml

Release: https://github.com/conda/conda/releases/tag/4.12.0

Bump to 4.12.0.

---

recipe/meta.yaml

In the [conda](https://github.com/conda/conda) repository, we recently removed our vendor-ed version of toolz and added cytoolz as a dependency. This also need to be reflected in the feed stock, hence this pull request.
Link to pull request for the removal of the vendor-ed version of toolz (an addition of cytoolz)
- https://github.com/conda/conda/pull/11589
Related to this pull request: https://github.com/conda-forge/conda-feedstock/pull/170

Moving cytoolz to be a run dependency

---

recipe/meta.yaml
recipe/run_test.bat

Bumps version for conda 4.14.0 release.
Depends on https://github.com/AnacondaRecipes/conda-feedstock/pull/7 & https://github.com/AnacondaRecipes/conda-feedstock/pull/8
#9 used my fork and didn't appear to trigger Prefect workflows, trying without fork.

Bump version to 4.14.0

---

recipe/meta.yaml

The latest **win-64** `conda-22.11.1` (build num 3) package on defaults has a problem that was caused by how `git` is installed on our **new** build system (Prefect). Building the package on the **old** build system (Concourse) should resolve the problem for now.
Bumping the build number and rebuilding win-64 on Concourse (all other platforms will be rebuilt on Prefect).
Concourse pipeine: https://concourse.build.corp.continuum.io/teams/main/pipelines/pyim_conda-22.11.1-b4

Rebuild to fix win-64 package on defaults

---

abs.yaml
recipe/meta.yaml

Required by [constructor](https://github.com/AnacondaRecipes/constructor-feedstock/pull/9)
Constructor requires `conda <23.1.0`. In order to build `constructor` for `python 3.11`, we need an earlier version of `conda` available on defaults.

Rebuild 22.11.1 for python 3.11

---

recipe/meta.yaml

Rebuild because the sha was wrong
No bump in build number necessary because the original build was never uploaded

Rebuild 23.5.1

---

recipe/meta.yaml

Patch release to fix regression running executable subcommands installed into non-base environments.
Xref https://github.com/conda/conda/issues/12849
Changelog https://github.com/conda/conda/releases/tag/23.7.3

Bump to v23.7.3

---

recipe/meta.yaml

Patch release to fix performance regression on WSL, `conda config --show-sources --json` sorting error, catch `PermissionError` when user's `$PATH` contains restricted paths, and use `os.scandir()` to find conda subcommands without `stat()` overhead.
Xref https://github.com/conda/conda/issues/12849
Changelog https://github.com/conda/conda/releases/tag/23.7.4

Bump version to 23.7.4

---

recipe/meta.yaml

Xrefs https://github.com/conda/conda/issues/13080

Release 23.9.0

---

recipe/meta.yaml

- Removes unnecessary dependency (pyopenssl), see https://github.com/conda/conda/pull/13170
- Sorts dependencies to mirror conda and conda-forge's recipes for easier maintenance
- Bump to latest version and update dependencies

Bump to 23.11.0

---

abs.yaml

Building build number 0 with --no-test to circumvent the cyclic dependency on conda-libmamba-solver.

temporary with --no-test

---

recipe/meta.yaml

conda 24.3.0
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.3.0)
- https://github.com/conda/conda/issues/13638

Bump to 24.3.0

---

recipe/meta.yaml

conda 24.4.0
- https://anaconda.atlassian.net/browse/PKG-4611
- [Upstream changelog/diff](https://github.com/conda/conda/compare/24.3.0...24.4.0)
- https://github.com/conda/conda/releases/tag/24.4.0
- Shipping signed exe stubs

Bump to 24.4.0

---

recipe/meta.yaml

conda 24.5.0
> [!WARNING]
> This is in draft mode and should not be merged until Monday, May 13th
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.5.0)
- https://github.com/conda/conda/issues/13870
- Remove `wheel` per https://github.com/conda/conda/pull/13684
- Add `frozendict` per https://github.com/conda/conda/pull/13766

Bump to 24.5.0

---

abs.yaml
recipe/meta.yaml

conda 24.9.0
- [PKG-5814](https://anaconda.atlassian.net/browse/PKG-5814)
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.9.0)
- n/a
- ...
[PKG-5814]: https://anaconda.atlassian.net/browse/PKG-5814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`conda 24.9.0` version bump

---

recipe/meta.yaml

conda 24.9.1
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.9.1)
- n/a

conda 24.9.1 version bump

---

recipe/meta.yaml

conda 24.11.0
- [PKG-5944](https://anaconda.atlassian.net/browse/PKG-5944) 
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.11.0)
- https://github.com/conda/conda/issues/14364
- n/a
- n/a
[PKG-5944]: https://anaconda.atlassian.net/browse/PKG-5944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bump conda to `24.11.0`

---

recipe/meta.yaml

conda 24.11.1
- [PKG-6508](https://anaconda.atlassian.net/browse/PKG-6508) 
- [Upstream changelog/diff](https://github.com/conda/conda/releases/tag/24.11.1)
- https://github.com/conda/conda/pull/14405
- Just a minor bugfix release for 24.11.x, fixing a regression with channel management.
[PKG-6508]: https://anaconda.atlassian.net/browse/PKG-6508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release conda 24.11.1.

---

recipe/meta.yaml

conda 25.3.0
- [PKG-7609](https://anaconda.atlassian.net/browse/PKG-7609) 
- ~Upstream changelog/diff~
- n/a
- https://github.com/conda/conda/issues/14694
- https://anaconda.slack.com/archives/C058SN1UBJ9/p1742913864257679
- Ensures the correct `conda` is invoked for `conda init`, i.e., use isolated mode to ensure we are invoking the installed package and not the source code
[PKG-7609]: https://anaconda.atlassian.net/browse/PKG-7609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Isolated mode

---

recipe/meta.yaml

conda 25.5.1
- [14838](https://github.com/conda/conda/issues/14838) 
- [conda](https://github.com/conda/conda)
- [conda 25.5.1 release notes](https://github.com/conda/conda/releases/tag/25.5.1)
- Special patch release need for a regression fix related to using aliases and `conda config --set`

Release 25.5.1
